version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - ./treasure-products:/var/www/html/treasure-products
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mystore123!
      MYSQL_DATABASE: my_store
      MYSQL_USER: root
      MYSQL_PASSWORD: Mystore123!
    volumes:
      - db_data:/var/lib/mysql
      - ./my_store.sql:/docker-entrypoint-initdb.d/my_store.sql:ro  # Preload the database schema
    ports:
      - "3306:3306"

volumes:
  db_data: