version: '3'

services:
  web:
    build: .
    container_name: php-mysql-nginx
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest 
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "root@000!"
      MYSQL_DATABASE: "my_store"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
