version: "3.8"

services:
  web:
    build: .
    container_name: php_nginx_app
    volumes:
      - ./php_mysql_nginx_docker_treasure-products:/var/www/html/php_mysql_nginx_docker_treasure-products
      - ./nginx/default.conf:/etc/nginx/sites-available/default
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Mystore123!
      MYSQL_DATABASE: my_store
    volumes:
      - db_data:/var/lib/mysql
      - ./my_store.sql:/docker-entrypoint-initdb.d/my_store.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: