version: '3.8'

services:
  # PHP Service
  php:
    build: .
    container_name: php_container
    volumes:
      - .:/var/www/html
    networks:
      - app_network

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app_network

  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: treasure_products
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
