version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: Mystore123!
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Mystore123!
      MYSQL_DATABASE: my_store
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
    driver: local
